services:
  - type: web
    name: tumorweb_backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: tumorweb_frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    startCommand: "nginx -g 'daemon off;'"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80
